version: "3"

services:
  # PostgreSQL database server
  psql:
    build:
      context: ./psql
      dockerfile: Dockerfile
    environment:
      - PGDATA:/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./psql/pg_hba.conf:/var/lib/postgres/data/pg_hba.conf
      - ./data/backup:/pgbackup
    restart: unless-stopped

  # Lapis
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - psql
    volumes:
      - ./app:/var/www
      - ./data:/var/data
    ports:
      - 9090:9090
    restart: unless-stopped
    environment: # Add environment variables here
      - LAPIS_CONFIG=${LAPIS_CONFIG}
      - SECRET=${SECRET}

    command: bash -c "/usr/local/bin/docker-entrypoint.sh ${LAPIS_CONFIG}"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/client
      - /client/node_modules

volumes:
  postgres:
  client:
